package org.folio.integration.kafka.consumer.filter.mmd.impl;

import static org.apache.commons.lang3.StringUtils.isBlank;

import lombok.RequiredArgsConstructor;
import org.folio.integration.kafka.consumer.filter.mmd.ModuleData;
import org.folio.integration.kafka.consumer.filter.mmd.ModuleDataProvider;
import org.springframework.boot.info.BuildProperties;

/**
 * {@link ModuleDataProvider} that reads the module name and version from Spring Boot's
 * {@link BuildProperties} bean, which is populated from the {@code META-INF/build-info.properties}
 * file generated by the {@code spring-boot-maven-plugin} build-info goal.
 *
 * <p>Uses {@code build.artifact} as the module name and {@code build.version} as the version.
 * Throws {@link IllegalStateException} if either value is blank.
 *
 * <p>This bean is only registered when a {@link BuildProperties} bean is present in the application
 * context (i.e. when {@code META-INF/build-info.properties} was generated at build time).
 */
@RequiredArgsConstructor
public class BuildPropertiesModuleDataProvider implements ModuleDataProvider {

  private final BuildProperties buildProperties;

  @Override
  public ModuleData getModuleData() {
    if (isBlank(buildProperties.getArtifact()) || isBlank(buildProperties.getVersion())) {
      throw new IllegalStateException("Build properties artifact or version is blank. Cannot provide module data.");
    } else {
      return new ModuleData(buildProperties.getArtifact(), buildProperties.getVersion());
    }
  }
}
